[2025-02-25 09:40:51,604: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 09:40:52,049: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 2.00 seconds... (1/100)

[2025-02-25 09:40:54,459: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 4.00 seconds... (2/100)

[2025-02-25 09:40:59,066: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 6.00 seconds... (3/100)

[2025-02-25 09:46:41,036: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 09:46:41,441: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 2.00 seconds... (1/100)

[2025-02-25 09:46:44,161: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 4.00 seconds... (2/100)

[2025-02-25 09:46:48,547: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 6.00 seconds... (3/100)

[2025-02-25 09:48:44,069: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 09:48:44,492: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 2.00 seconds... (1/100)

[2025-02-25 09:48:46,941: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 4.00 seconds... (2/100)

[2025-02-25 09:49:52,823: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 09:49:53,297: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 2.00 seconds... (1/100)

[2025-02-25 09:49:55,714: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 4.00 seconds... (2/100)

[2025-02-25 09:50:00,103: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 6.00 seconds... (3/100)

[2025-02-25 09:53:50,602: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 09:53:53,711: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error 113 connecting to redis:6379. No route to host..
Trying again in 2.00 seconds... (1/100)

[2025-02-25 09:53:56,094: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 4.00 seconds... (2/100)

[2025-02-25 09:54:52,107: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 09:54:52,555: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 2.00 seconds... (1/100)

[2025-02-25 09:54:54,925: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 4.00 seconds... (2/100)

[2025-02-25 09:54:59,526: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 6.00 seconds... (3/100)

[2025-02-25 09:55:11,733: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 09:55:12,101: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 2.00 seconds... (1/100)

[2025-02-25 09:55:14,516: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 4.00 seconds... (2/100)

[2025-02-25 09:59:22,429: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 09:59:22,832: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 2.00 seconds... (1/100)

[2025-02-25 09:59:25,226: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 4.00 seconds... (2/100)

[2025-02-25 09:59:29,604: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 6.00 seconds... (3/100)

[2025-02-25 10:01:37,408: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 10:01:37,780: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/1: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 2.00 seconds... (1/100)

[2025-02-25 10:01:40,196: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/1: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 4.00 seconds... (2/100)

[2025-02-25 10:01:44,671: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/1: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 6.00 seconds... (3/100)

[2025-02-25 10:05:28,082: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 10:05:28,505: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 2.00 seconds... (1/100)

[2025-02-25 10:05:30,922: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 4.00 seconds... (2/100)

[2025-02-25 10:06:40,289: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 10:06:40,301: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-02-25 10:06:40,302: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 10:06:40,304: INFO/MainProcess] mingle: searching for neighbors
[2025-02-25 10:06:41,316: INFO/MainProcess] mingle: all alone
[2025-02-25 10:06:41,323: INFO/MainProcess] celery@1c470f00a010 ready.
[2025-02-25 10:06:42,404: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-02-25 10:16:37,585: INFO/MainProcess] Task user.tasks.send_new_user_email[dbb16ab9-8e99-4af0-8efd-a290152f70a6] received
[2025-02-25 10:16:40,336: ERROR/ForkPoolWorker-7] Task user.tasks.send_new_user_email[dbb16ab9-8e99-4af0-8efd-a290152f70a6] raised unexpected: SMTPAuthenticationError(535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials a640c23a62f3a-abed204f6edsm113321166b.128 - gsmtp')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/user/tasks.py", line 16, in send_new_user_email
    send_email('Verify Email',
  File "/app/user/utils.py", line 10, in send_email
    msg.send(fail_silently=False)
  File "/usr/local/lib/python3.10/site-packages/django/core/mail/message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 95, in open
    self.connection.login(self.username, self.password)
  File "/usr/local/lib/python3.10/smtplib.py", line 750, in login
    raise last_exception
  File "/usr/local/lib/python3.10/smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "/usr/local/lib/python3.10/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials a640c23a62f3a-abed204f6edsm113321166b.128 - gsmtp')
[2025-02-25 10:25:56,876: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 10:25:56,888: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-02-25 10:25:56,889: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 10:25:56,891: INFO/MainProcess] mingle: searching for neighbors
[2025-02-25 10:25:57,899: INFO/MainProcess] mingle: all alone
[2025-02-25 10:25:57,925: INFO/MainProcess] celery@8b2c6eeade56 ready.
[2025-02-25 10:25:58,916: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-02-25 10:26:29,171: INFO/MainProcess] Task user.tasks.send_new_user_email[57493679-13d6-481d-9076-8a0521a285de] received
[2025-02-25 10:26:33,089: INFO/ForkPoolWorker-7] Task user.tasks.send_new_user_email[57493679-13d6-481d-9076-8a0521a285de] succeeded in 3.9166674119987874s: None
[2025-02-25 10:30:44,519: INFO/MainProcess] Task user.tasks.send_password_reset_email[0bde8b44-240e-4fdd-acbe-8a8b51764c15] received
[2025-02-25 10:30:47,447: INFO/ForkPoolWorker-7] Task user.tasks.send_password_reset_email[0bde8b44-240e-4fdd-acbe-8a8b51764c15] succeeded in 2.9263268989998323s: None
[2025-02-25 10:32:48,260: INFO/MainProcess] Task user.tasks.send_password_reset_email[6da96235-ad76-464d-b09b-f46ddab47932] received
[2025-02-25 10:32:51,140: INFO/ForkPoolWorker-7] Task user.tasks.send_password_reset_email[6da96235-ad76-464d-b09b-f46ddab47932] succeeded in 2.8781312690007326s: None
[2025-02-25 10:51:27,194: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 10:51:27,209: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-02-25 10:51:27,210: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 10:51:27,211: INFO/MainProcess] mingle: searching for neighbors
[2025-02-25 10:51:28,220: INFO/MainProcess] mingle: all alone
[2025-02-25 10:51:28,228: INFO/MainProcess] celery@87a8b1d9ed44 ready.
[2025-02-25 10:51:28,967: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-02-25 10:52:13,056: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 10:52:13,066: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-02-25 10:52:13,067: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-02-25 10:52:13,068: INFO/MainProcess] mingle: searching for neighbors
[2025-02-25 10:52:14,073: INFO/MainProcess] mingle: all alone
[2025-02-25 10:52:14,080: INFO/MainProcess] celery@976f5492b205 ready.
[2025-02-25 10:52:14,586: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-02-25 11:58:30,794: INFO/MainProcess] Task user.tasks.send_password_reset_email[502c3023-8020-4749-a333-96f1771e7ee9] received
[2025-02-25 11:58:33,354: INFO/MainProcess] Task user.tasks.send_new_user_email[0d68df49-4f82-4bbe-b6f1-451b781eb3bb] received
[2025-02-25 11:58:34,444: INFO/ForkPoolWorker-7] Task user.tasks.send_password_reset_email[502c3023-8020-4749-a333-96f1771e7ee9] succeeded in 3.6479478840010415s: None
[2025-02-25 11:58:36,585: INFO/ForkPoolWorker-8] Task user.tasks.send_new_user_email[0d68df49-4f82-4bbe-b6f1-451b781eb3bb] succeeded in 3.2294521490002808s: None
[2025-02-25 12:00:02,093: INFO/MainProcess] Task user.tasks.send_password_reset_email[1eabe4c4-a57c-413c-b0c1-9adac77684c1] received
[2025-02-25 12:00:04,325: INFO/MainProcess] Task user.tasks.send_new_user_email[7a376fbc-9aca-42b5-8000-3d9a3e61dacb] received
[2025-02-25 12:00:04,770: INFO/ForkPoolWorker-7] Task user.tasks.send_password_reset_email[1eabe4c4-a57c-413c-b0c1-9adac77684c1] succeeded in 2.6761103749995527s: None
[2025-02-25 12:00:06,990: INFO/ForkPoolWorker-8] Task user.tasks.send_new_user_email[7a376fbc-9aca-42b5-8000-3d9a3e61dacb] succeeded in 2.6622302270006912s: None
[2025-02-25 12:01:41,900: INFO/MainProcess] Task user.tasks.send_password_reset_email[2a7de805-311c-4f4b-b707-1a54bead4114] received
[2025-02-25 12:01:44,330: INFO/MainProcess] Task user.tasks.send_new_user_email[5ddc828e-ef95-4bb5-a079-298e2383e66d] received
[2025-02-25 12:01:44,681: INFO/ForkPoolWorker-7] Task user.tasks.send_password_reset_email[2a7de805-311c-4f4b-b707-1a54bead4114] succeeded in 2.779263282998727s: None
[2025-02-25 12:01:46,935: INFO/ForkPoolWorker-8] Task user.tasks.send_new_user_email[5ddc828e-ef95-4bb5-a079-298e2383e66d] succeeded in 2.603524664998986s: None
[2025-02-25 12:05:33,212: INFO/MainProcess] Task user.tasks.send_password_reset_email[6801c732-e135-4226-a8db-1f835bd5d8c1] received
[2025-02-25 12:05:35,774: INFO/MainProcess] Task user.tasks.send_new_user_email[913bc688-1926-4868-8908-3bf9f4f49d3c] received
[2025-02-25 12:05:37,332: INFO/ForkPoolWorker-7] Task user.tasks.send_password_reset_email[6801c732-e135-4226-a8db-1f835bd5d8c1] succeeded in 4.118317390999437s: None
[2025-02-25 12:05:39,633: INFO/ForkPoolWorker-8] Task user.tasks.send_new_user_email[913bc688-1926-4868-8908-3bf9f4f49d3c] succeeded in 3.8581337350005924s: None
[2025-02-25 12:06:36,231: INFO/MainProcess] Task user.tasks.send_password_reset_email[915a34b3-6656-4a04-9c54-3290f1a26a5c] received
[2025-02-25 12:06:38,422: INFO/MainProcess] Task user.tasks.send_new_user_email[a9f9e10d-d085-4520-b18e-dabe3e927ebf] received
[2025-02-25 12:06:39,414: INFO/ForkPoolWorker-7] Task user.tasks.send_password_reset_email[915a34b3-6656-4a04-9c54-3290f1a26a5c] succeeded in 3.181109394001396s: None
[2025-02-25 12:06:41,821: INFO/ForkPoolWorker-8] Task user.tasks.send_new_user_email[a9f9e10d-d085-4520-b18e-dabe3e927ebf] succeeded in 3.3968947519970243s: None
[2025-02-25 12:07:19,788: INFO/MainProcess] Task user.tasks.send_password_reset_email[454f10ee-9b60-48e1-8701-8aca1478117c] received
[2025-02-25 12:07:21,970: INFO/MainProcess] Task user.tasks.send_new_user_email[47807fc0-b172-4245-b056-42da69d84846] received
[2025-02-25 12:07:24,114: INFO/ForkPoolWorker-7] Task user.tasks.send_password_reset_email[454f10ee-9b60-48e1-8701-8aca1478117c] succeeded in 4.324666047999926s: None
[2025-02-25 12:07:25,475: INFO/ForkPoolWorker-8] Task user.tasks.send_new_user_email[47807fc0-b172-4245-b056-42da69d84846] succeeded in 3.5030415229994105s: None
[2025-02-25 12:10:20,325: INFO/MainProcess] Task user.tasks.send_password_reset_email[b747c1a5-9959-4157-b57d-4fce6863c8e9] received
[2025-02-25 12:10:22,624: INFO/MainProcess] Task user.tasks.send_new_user_email[db90b49f-be46-43ec-9ed4-ae3641d7fcb3] received
[2025-02-25 12:10:23,956: INFO/ForkPoolWorker-7] Task user.tasks.send_password_reset_email[b747c1a5-9959-4157-b57d-4fce6863c8e9] succeeded in 3.6293672120009433s: None
[2025-02-25 12:10:27,070: INFO/ForkPoolWorker-8] Task user.tasks.send_new_user_email[db90b49f-be46-43ec-9ed4-ae3641d7fcb3] succeeded in 4.444370106000861s: None
[2025-03-06 22:25:52,714: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-03-06 22:25:52,719: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-03-06 22:25:52,719: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-03-06 22:25:52,720: INFO/MainProcess] mingle: searching for neighbors
[2025-03-06 22:25:53,728: INFO/MainProcess] mingle: all alone
[2025-03-06 22:25:53,764: INFO/MainProcess] celery@818bfd811fcb ready.
[2025-03-06 22:25:54,135: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-03-06 22:26:08,391: INFO/MainProcess] sync with celery@685862c77b58
[2025-03-06 22:43:53,317: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-03-06 22:43:53,321: INFO/MainProcess] Connected to redis://redis:6379/0
[2025-03-06 22:43:53,322: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-03-06 22:43:53,323: INFO/MainProcess] mingle: searching for neighbors
[2025-03-06 22:43:54,328: INFO/MainProcess] mingle: all alone
[2025-03-06 22:43:54,337: INFO/MainProcess] celery@53681e407d3c ready.
[2025-03-06 22:43:59,014: INFO/MainProcess] Events of group {task} enabled by remote.
[2025-03-06 22:44:08,465: INFO/MainProcess] sync with celery@f9aaa8b518a1
